"""drop_kb_document_id_from_documents

Revision ID: 976391a750a9
Revises: aa466cc7e646
Create Date: 2026-05-02 10:17:13.975582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '976391a750a9'
down_revision: Union[str, None] = 'aa466cc7e646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'kb_document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('kb_document_id', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
