"""add_source_type_and_nullable_s3_key_to_documents

Revision ID: 46873509dc6b
Revises: a0bcac69c59e
Create Date: 2026-04-26 10:37:06.601843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46873509dc6b'
down_revision: Union[str, None] = 'a0bcac69c59e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_type', sa.Text(), nullable=False, server_default='pdf'))
    op.alter_column('documents', 's3_key',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 's3_key',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('documents', 'source_type')
    # ### end Alembic commands ###
