"""add_cascade_delete_to_questions_document_id_fkey

Revision ID: a0bcac69c59e
Revises: 56656963c65f
Create Date: 2026-04-17 15:06:09.880919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0bcac69c59e'
down_revision: Union[str, None] = '56656963c65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('questions_document_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_document_id_fkey'), 'questions', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
